INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('1', 'Начално');
INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('2', 'Основно');
INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('3', 'Средно');
INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('4', 'Средно специално');
INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('5', 'Професионален бакалавър');
INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('6', 'Бакалавър');
INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('7', 'Магистър');
INSERT INTO `NOM_ACADEMIC_DEGREE` (`ID`, `NAME`) VALUES ('8', 'Доктор');

INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('1', 'Информатика');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('2', 'Компютърни науки');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('3', 'Софтуерно инженерство');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('4', 'Информационни системи');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('5', 'Математика');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('6', 'Приложна математика');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('7', 'Статистика');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('8', 'Математика и информатика (редовно)');
INSERT INTO `NOM_ACADEMIC_SPECIALIZATION` (`ID`, `NAME`) VALUES ('9', 'Математика и информатика (задочно)');

INSERT INTO `NOM_CARDHOLDER_TYPE` (`ID`, `NAME`) VALUES ('1', 'Студент');
INSERT INTO `NOM_CARDHOLDER_TYPE` (`ID`, `NAME`) VALUES ('2', 'Преподавател');
INSERT INTO `NOM_CARDHOLDER_TYPE` (`ID`, `NAME`) VALUES ('3', 'Служител');
