CREATE TABLE `StudentBuildingMonitor`.`NOM_ACADEMIC_DEGREE` (
   `ID` INT NOT NULL , 
   `NAME` VARCHAR(50) NOT NULL ) ENGINE = InnoDB;

CREATE TABLE `StudentBuildingMonitor`.`NOM_ACADEMIC_SPECIALIZATION` ( 
  `ID` INT NOT NULL , 
  `NAME` VARCHAR(50) NOT NULL ) ENGINE = InnoDB;

CREATE TABLE `StudentBuildingMonitor`.`NOM_CARDHOLDER_TYPE` ( 
  `ID` INT NOT NULL , 
  `NAME` VARCHAR(50) NOT NULL ) ENGINE = InnoDB;

CREATE TABLE `StudentBuildingMonitor`.`CARDHOLDERS` ( 
  `ID` INT NOT NULL , 
  `NAME` VARCHAR(50) NOT NULL , 
  `BIRTH_DATE` DATE NOT NULL , 
  `EMAIL` VARCHAR(50) NOT NULL , 
  `ACADEMIC_DEGREE` INT NOT NULL , 
  `TYPE` INT NOT NULL ) ENGINE = InnoDB;

ALTER TABLE `CARDHOLDERS` ADD UNIQUE INDEX(`ID`);

CREATE TABLE `StudentBuildingMonitor`.`STUDENTS` ( 
  `ID` INT NOT NULL , 
  `CARDHOLDER_ID` INT NOT NULL , 
  `STUDY_DEGREE` INT NOT NULL , 
  `FACULTY_NUM` VARCHAR(10) NOT NULL , 
  `YEAR` INT , 
  `GROUP` INT ) ENGINE = InnoDB;

ALTER TABLE `STUDENTS` ADD UNIQUE INDEX(`ID`);

CREATE TABLE `StudentBuildingMonitor`.`TUTORS` ( 
  `ID` INT NOT NULL , 
  `CARDHOLDER_ID` INT NOT NULL , 
  `TEACHING_SINCE` DATE NOT NULL , 
  `PHONE_NUM` VARCHAR(15) NOT NULL , 
  `CABINET` VARCHAR(10) ) ENGINE = InnoDB;

ALTER TABLE `TUTORS` ADD UNIQUE INDEX(`ID`);

CREATE TABLE `StudentBuildingMonitor`.`EMPLOYEES` ( 
  `ID` INT NOT NULL , 
  `CARDHOLDER_ID` INT NOT NULL , 
  `PHONE_NUM` VARCHAR(15) NOT NULL , 
  `POSITION` VARCHAR(50) ) ENGINE = InnoDB;

ALTER TABLE `EMPLOYEES` ADD UNIQUE INDEX(`ID`);

CREATE TABLE `StudentBuildingMonitor`.`PASSAGES` ( 
  `ID` INT NOT NULL , 
  `CARDHOLDER_ID` INT NOT NULL , 
  `DATE_TIME` DATETIME NOT NULL , 
  `ENTERING` INT NOT NULL ,
  `BODY_TEMPERATURE` INT ,) ENGINE = InnoDB;

ALTER TABLE `PASSAGES` ADD UNIQUE INDEX(`ID`);

CREATE TABLE `StudentBuildingMonitor`.`COURSES` ( 
  `ID` INT NOT NULL , 
  `NAME` VARCHAR(50) NOT NULL , 
  `START_DATE` DATE NOT NULL , 
  `END_DATE` DATE NOT NULL , 
  `LECTURE_HALL` VARCHAR(10) NOT NULL,
  `MANDATORY` INT NOT NULL ) ENGINE = InnoDB;

ALTER TABLE `COURSES` ADD UNIQUE INDEX(`ID`);

CREATE TABLE `StudentBuildingMonitor`.`STUDENTS_TAKING_COURSES` ( 
  `STUDENT_ID` INT NOT NULL , 
  `COURSE_ID` INT NOT NULL ) ENGINE = InnoDB;

CREATE TABLE `StudentBuildingMonitor`.`TUTORS_TEACHING_COURSES` ( 
  `TUTOR_ID` INT NOT NULL , 
  `COURSE_ID` INT NOT NULL ) ENGINE = InnoDB;